apiVersion: apps/v1
kind: Deployment
metadata:
  name: cn-service
  labels:
    app: cn-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cn-service
  template:
    metadata:
      labels:
        app: cn-service
        #environment: {{ .Values.environment }}
    spec:
      containers:
        - name: cn-service
          image: rleibold/robs_repo:cn-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          #env:
          #  - name: apphost
          #    value: {{ .Values.apphost }}
          #  - name: appenvironment
          #    value: {{ .Values.environment}}
          #    readinessProbe:
          #      httpGet:
          #        path: /health/ready
          #        port: {{ .Values.container.port }}
          #      initialDelaySeconds: {{ .Values.container.probeDelay }}
          #    livenessProbe:
          #      httpGet:
          #        path: /health/live
          #        port: {{ .Values.container.port }}
          #      initialDelaySeconds: {{ .Values.container.probeDelay }}
