apiVersion: v1
kind: Service
metadata:
  name: cn-service
  labels:
    app: cn-service
spec:
  ports:
  - port: 80
    #protocol: TCP
    #targetPort: {{ .Values.container.port }}
  selector:
    app: cn-service
  type: LoadBalancer
